name: test scripts

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        config: [
            astyle-cleanliness,
            check_autotest_options,
            logger_metadata,
            param_parse,
            param-file-validation,
            python-cleanliness,
            shellcheck,
            validate_board_list,
          ]
    steps:
      # git checkout the PR
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: pip  # caching pip dependencies
          pip-install: flake8 lxml pexpect

      - name: Install astyle
        if: matrix.config == 'astyle-cleanliness'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install --yes astyle

      - name: test ${{matrix.config}}
        env:
          CI_BUILD_TARGET: check_autotest_options
        shell: bash
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          Tools/scripts/build_ci.sh
      - name: param_parse
        env:
          CI_BUILD_TARGET: param_parse
        shell: bash
        run: Tools/scripts/build_ci.sh
      - name: python-cleanliness
        env:
          CI_BUILD_TARGET: python-cleanliness
        shell: bash
        run: Tools/scripts/build_ci.sh
      - name: astyle-cleanliness
        env:
          CI_BUILD_TARGET: astyle-cleanliness
        shell: bash
        run: Tools/scripts/build_ci.sh
      - name: validate_board_list
        env:
          CI_BUILD_TARGET: validate_board_list
        shell: bash
        run: Tools/scripts/build_ci.sh
      - name: logger_metadata
        env:
          CI_BUILD_TARGET: logger_metadata
        shell: bash
        run: Tools/scripts/build_ci.sh
